source "http://rubygems.org"

ruby "2.2.2"
gem "rails"

gem "active_link_to"
gem "analytics-ruby"
gem "awesome_print"
gem "aws-sdk", "< 2.0"
gem "bourbon"
gem "buffer", :github => "bufferapp/buffer-ruby"
gem "cancancan"
gem "clockwork"
gem "coffee-rails"
gem "devise"
gem "devise-async"
gem "devise_invitable"
gem "doorkeeper"
gem "email_validator"
gem "ember-rails"
gem "ember-source"
gem "eventbrite-client", github: "jordanhudgens/eventbrite-client.rb"
gem "font_assets"
gem "font-awesome-rails"
gem "geocoder"
gem "gibberish"
gem "gibbon"
gem "google_timezone"
gem "highline"
gem "jbuilder"
gem "jquery-rails"
gem "local_time", github: "basecamp/local_time"
gem "momentjs-rails"
gem "neat"
gem "normalize-rails"
gem "paperclip"
gem "paranoia"
gem "pg"
gem "pickadate-rails"
gem "puma"
gem "rack-cors", require: "rack/cors"
gem "rest-client"
gem "roadie"
gem "roadie-rails", github: "afeld/roadie-rails", branch: "asset_host"
gem "sass-rails"
gem "sentry-raven", git: "https://github.com/getsentry/raven-ruby.git"
gem "sidekiq"
gem "sidekiq_mailer"
gem "sprockets-rails"
gem "uglifier"

group :development, :test do
  gem "byebug"
  gem "dotenv-rails"
  gem "factory_girl_rails"
  gem "foreman"
  gem "letter_opener_web"
  gem "quiet_assets"
  gem "rspec-rails"
  gem "spring"
  gem "sinatra"
end

group :test do
  gem "capybara"
  gem "database_cleaner"
  gem "faker"
  gem "guard"
  gem "guard-rspec"
  gem "rb-fsevent"
  gem "terminal-notifier-guard"
  gem "webmock"
end

group :production do
  gem "rails_12factor"
end
